<?php
$mime_db = [Array("name"=>"3D Crossword Plugin","mime"=>"application/vnd.hzn-3d-crossword","extension"=>[".x3d"]),
Array("name"=>"3GP","mime"=>"video/3gpp","extension"=>[".3gp"]),
Array("name"=>"3GP2","mime"=>"video/3gpp2","extension"=>[".3g2"]),
Array("name"=>"3GPP MSEQ File","mime"=>"application/vnd.mseq","extension"=>[".mseq"]),
Array("name"=>"3M Post It Notes","mime"=>"application/vnd.3m.post-it-notes","extension"=>[".pwn"]),
Array("name"=>"3rd Generation Partnership Project - Pic Large","mime"=>"application/vnd.3gpp.pic-bw-large","extension"=>[".plb"]),
Array("name"=>"3rd Generation Partnership Project - Pic Small","mime"=>"application/vnd.3gpp.pic-bw-small","extension"=>[".psb"]),
Array("name"=>"3rd Generation Partnership Project - Pic Var","mime"=>"application/vnd.3gpp.pic-bw-var","extension"=>[".pvb"]),
Array("name"=>"3rd Generation Partnership Project - Transaction Capabilities Application Part","mime"=>"application/vnd.3gpp2.tcap","extension"=>[".tcap"]),
Array("name"=>"7-Zip","mime"=>"application/x-7z-compressed","extension"=>[".7z"]),
Array("name"=>"AbiWord","mime"=>"application/x-abiword","extension"=>[".abw"]),
Array("name"=>"Ace Archive","mime"=>"application/x-ace-compressed","extension"=>[".ace"]),
Array("name"=>"Active Content Compression","mime"=>"application/vnd.americandynamics.acc","extension"=>[".acc"]),
Array("name"=>"ACU Cobol","mime"=>"application/vnd.acucobol","extension"=>[".acu"]),
Array("name"=>"ACU Cobol","mime"=>"application/vnd.acucorp","extension"=>[".atc"]),
Array("name"=>"Adaptive differential pulse-code modulation","mime"=>"audio/adpcm","extension"=>[".adp"]),
Array("name"=>"Adobe (Macropedia) Authorware - Binary File","mime"=>"application/x-authorware-bin","extension"=>[".aab"]),
Array("name"=>"Adobe (Macropedia) Authorware - Map","mime"=>"application/x-authorware-map","extension"=>[".aam"]),
Array("name"=>"Adobe (Macropedia) Authorware - Segment File","mime"=>"application/x-authorware-seg","extension"=>[".aas"]),
Array("name"=>"Adobe AIR Application","mime"=>"application/vnd.adobe.air-application-installer-package+zip","extension"=>[".air"]),
Array("name"=>"Adobe Flash","mime"=>"application/x-shockwave-flash","extension"=>[".swf"]),
Array("name"=>"Adobe Flex Project","mime"=>"application/vnd.adobe.fxp","extension"=>[".fxp"]),
Array("name"=>"Adobe Portable Document Format","mime"=>"application/pdf","extension"=>[".pdf"]),
Array("name"=>"Adobe PostScript Printer Description File Format","mime"=>"application/vnd.cups-ppd","extension"=>[".ppd"]),
Array("name"=>"Adobe Shockwave Player","mime"=>"application/x-director","extension"=>[".dir"]),
Array("name"=>"Adobe XML Data Package","mime"=>"application/vnd.adobe.xdp+xml","extension"=>[".xdp"]),
Array("name"=>"Adobe XML Forms Data Format","mime"=>"application/vnd.adobe.xfdf","extension"=>[".xfdf"]),
Array("name"=>"Advanced Audio Coding (AAC)","mime"=>"audio/x-aac","extension"=>[".aac"]),
Array("name"=>"Ahead AIR Application","mime"=>"application/vnd.ahead.space","extension"=>[".ahead"]),
Array("name"=>"AirZip FileSECURE","mime"=>"application/vnd.airzip.filesecure.azf","extension"=>[".azf"]),
Array("name"=>"AirZip FileSECURE","mime"=>"application/vnd.airzip.filesecure.azs","extension"=>[".azs"]),
Array("name"=>"Amazon Kindle eBook format","mime"=>"application/vnd.amazon.ebook","extension"=>[".azw"]),
Array("name"=>"AmigaDE","mime"=>"application/vnd.amiga.ami","extension"=>[".ami"]),
Array("name"=>"Andrew Toolkit","mime"=>"application/andrew-inset","extension"=>[".???"]),
Array("name"=>"Android Package Archive","mime"=>"application/vnd.android.package-archive","extension"=>[".apk"]),
Array("name"=>"ANSER-WEB Terminal Client - Certificate Issue","mime"=>"application/vnd.anser-web-certificate-issue-initiation","extension"=>[".cii"]),
Array("name"=>"ANSER-WEB Terminal Client - Web Funds Transfer","mime"=>"application/vnd.anser-web-funds-transfer-initiation","extension"=>[".fti"]),
Array("name"=>"Antix Game Player","mime"=>"application/vnd.antix.game-component","extension"=>[".atx"]),
Array("name"=>"Apple Disk Image","mime"=>"application/x-apple-diskimage","extension"=>[".dmg"]),
Array("name"=>"Apple Installer Package","mime"=>"application/vnd.apple.installer+xml","extension"=>[".mpkg"]),
Array("name"=>"Applixware","mime"=>"application/applixware","extension"=>[".aw"]),
Array("name"=>"Archipelago Lesson Player","mime"=>"application/vnd.hhe.lesson-player","extension"=>[".les"]),
Array("name"=>"Archive document - Multiple Fils Embedded","mime"=>"application/x-freearc","extension"=>[".arc"]),
Array("name"=>"Arista Networks Software Image","mime"=>"application/vnd.aristanetworks.swi","extension"=>[".swi"]),
Array("name"=>"Assembler Source File","mime"=>"text/x-asm","extension"=>[".s"]),
Array("name"=>"Atom Publishing Protocol","mime"=>"application/atomcat+xml","extension"=>[".atomcat"]),
Array("name"=>"Atom Publishing Protocol Service Document","mime"=>"application/atomsvc+xml","extension"=>[".atomsvc"]),
Array("name"=>"Atom Syndication Format","mime"=>"application/atom+xml","extension"=>[".atom",".xml"]),
Array("name"=>"Attribute Certificate","mime"=>"application/pkix-attr-cert","extension"=>[".ac"]),
Array("name"=>"Audio Interchange File Format","mime"=>"audio/x-aiff","extension"=>[".aif"]),
Array("name"=>"Audio Video Interleave (AVI)","mime"=>"video/x-msvideo","extension"=>[".avi"]),
Array("name"=>"Audiograph","mime"=>"application/vnd.audiograph","extension"=>[".aep"]),
Array("name"=>"AutoCAD DXF","mime"=>"image/vnd.dxf","extension"=>[".dxf"]),
Array("name"=>"Autodesk Design Web Format (DWF)","mime"=>"model/vnd.dwf","extension"=>[".dwf"]),
Array("name"=>"AV1 Image File","mime"=>"image/avif","extension"=>[".avif"]),
Array("name"=>"BAS Partitur Format","mime"=>"text/plain-bas","extension"=>[".par"]),
Array("name"=>"Binary CPIO Archive","mime"=>"application/x-bcpio","extension"=>[".bcpio"]),
Array("name"=>"Binary Data","mime"=>"application/octet-stream","extension"=>[".bin"]),
Array("name"=>"Bitmap Image File","mime"=>"image/bmp","extension"=>[".bmp"]),
Array("name"=>"BitTorrent","mime"=>"application/x-bittorrent","extension"=>[".torrent"]),
Array("name"=>"Blackberry COD File","mime"=>"application/vnd.rim.cod","extension"=>[".cod"]),
Array("name"=>"Blueice Research Multipass","mime"=>"application/vnd.blueice.multipass","extension"=>[".mpm"]),
Array("name"=>"BMI Drawing Data Interchange","mime"=>"application/vnd.bmi","extension"=>[".bmi"]),
Array("name"=>"Bourne Shell Script","mime"=>"application/x-sh","extension"=>[".sh"]),
Array("name"=>"BTIF","mime"=>"image/prs.btif","extension"=>[".btif"]),
Array("name"=>"BusinessObjects","mime"=>"application/vnd.businessobjects","extension"=>[".rep"]),
Array("name"=>"Bzip Archive","mime"=>"application/x-bzip","extension"=>[".bz"]),
Array("name"=>"Bzip2 Archive","mime"=>"application/x-bzip2","extension"=>[".bz2"]),
Array("name"=>"C Shell Script","mime"=>"application/x-csh","extension"=>[".csh"]),
Array("name"=>"C Source File","mime"=>"text/x-c","extension"=>[".c"]),
Array("name"=>"CambridgeSoft Chem Draw","mime"=>"application/vnd.chemdraw+xml","extension"=>[".cdxml"]),
Array("name"=>"Cascading Style Sheets (CSS)","mime"=>"text/css","extension"=>[".css"]),
Array("name"=>"CD Audio","mime"=>"application/x-cdf","extension"=>[".cda"]),
Array("name"=>"ChemDraw eXchange file","mime"=>"chemical/x-cdx","extension"=>[".cdx"]),
Array("name"=>"Chemical Markup Language","mime"=>"chemical/x-cml","extension"=>[".cml"]),
Array("name"=>"Chemical Style Markup Language","mime"=>"chemical/x-csml","extension"=>[".csml"]),
Array("name"=>"CIM Database","mime"=>"application/vnd.contact.cmsg","extension"=>[".cdbcmsg"]),
Array("name"=>"Claymore Data Files","mime"=>"application/vnd.claymore","extension"=>[".cla"]),
Array("name"=>"Clonk Game","mime"=>"application/vnd.clonk.c4group","extension"=>[".c4g"]),
Array("name"=>"Close Captioning - Subtitle","mime"=>"image/vnd.dvb.subtitle","extension"=>[".sub"]),
Array("name"=>"Cloud Data Management Interface (CDMI) - Capability","mime"=>"application/cdmi-capability","extension"=>[".cdmia"]),
Array("name"=>"Cloud Data Management Interface (CDMI) - Contaimer","mime"=>"application/cdmi-container","extension"=>[".cdmic"]),
Array("name"=>"Cloud Data Management Interface (CDMI) - Domain","mime"=>"application/cdmi-domain","extension"=>[".cdmid"]),
Array("name"=>"Cloud Data Management Interface (CDMI) - Object","mime"=>"application/cdmi-object","extension"=>[".cdmio"]),
Array("name"=>"Cloud Data Management Interface (CDMI) - Queue","mime"=>"application/cdmi-queue","extension"=>[".cdmiq"]),
Array("name"=>"ClueTrust CartoMobile - Config","mime"=>"application/vnd.cluetrust.cartomobile-config","extension"=>[".c11amc"]),
Array("name"=>"ClueTrust CartoMobile - Config Package","mime"=>"application/vnd.cluetrust.cartomobile-config-pkg","extension"=>[".c11amz"]),
Array("name"=>"CMU Image","mime"=>"image/x-cmu-raster","extension"=>[".ras"]),
Array("name"=>"COLLADA","mime"=>"model/vnd.collada+xml","extension"=>[".dae"]),
Array("name"=>"Comma-Seperated Values","mime"=>"text/csv","extension"=>[".csv"]),
Array("name"=>"Compact Pro","mime"=>"application/mac-compactpro","extension"=>[".cpt"]),
Array("name"=>"Compiled Wireless Markup Language (WMLC)","mime"=>"application/vnd.wap.wmlc","extension"=>[".wmlc"]),
Array("name"=>"Computer Graphics Metafile","mime"=>"image/cgm","extension"=>[".cgm"]),
Array("name"=>"CoolTalk","mime"=>"x-conference/x-cooltalk","extension"=>[".ice"]),
Array("name"=>"Corel Metafile Exchange (CMX)","mime"=>"image/x-cmx","extension"=>[".cmx"]),
Array("name"=>"CorelXARA","mime"=>"application/vnd.xara","extension"=>[".xar"]),
Array("name"=>"CosmoCaller","mime"=>"application/vnd.cosmocaller","extension"=>[".cmc"]),
Array("name"=>"CPIO Archive","mime"=>"application/x-cpio","extension"=>[".cpio"]),
Array("name"=>"CrickSoftware - Clicker","mime"=>"application/vnd.crick.clicker","extension"=>[".clkx"]),
Array("name"=>"CrickSoftware - Clicker - Keyboard","mime"=>"application/vnd.crick.clicker.keyboard","extension"=>[".clkk"]),
Array("name"=>"CrickSoftware - Clicker - Palette","mime"=>"application/vnd.crick.clicker.palette","extension"=>[".clkp"]),
Array("name"=>"CrickSoftware - Clicker - Template","mime"=>"application/vnd.crick.clicker.template","extension"=>[".clkt"]),
Array("name"=>"CrickSoftware - Clicker - Wordbank","mime"=>"application/vnd.crick.clicker.wordbank","extension"=>[".clkw"]),
Array("name"=>"Critical Tools - PERT Chart EXPERT","mime"=>"application/vnd.criticaltools.wbs+xml","extension"=>[".wbs"]),
Array("name"=>"CryptoNote","mime"=>"application/vnd.rig.cryptonote","extension"=>[".cryptonote"]),
Array("name"=>"Crystallographic Interchange Format","mime"=>"chemical/x-cif","extension"=>[".cif"]),
Array("name"=>"CrystalMaker Data Format","mime"=>"chemical/x-cmdf","extension"=>[".cmdf"]),
Array("name"=>"CU-SeeMe","mime"=>"application/cu-seeme","extension"=>[".cu"]),
Array("name"=>"CU-Writer","mime"=>"application/prs.cww","extension"=>[".cww"]),
Array("name"=>"Curl - Applet","mime"=>"text/vnd.curl","extension"=>[".curl"]),
Array("name"=>"Curl - Detached Applet","mime"=>"text/vnd.curl.dcurl","extension"=>[".dcurl"]),
Array("name"=>"Curl - Manifest File","mime"=>"text/vnd.curl.mcurl","extension"=>[".mcurl"]),
Array("name"=>"Curl - Source Code","mime"=>"text/vnd.curl.scurl","extension"=>[".scurl"]),
Array("name"=>"CURL Applet","mime"=>"application/vnd.curl.car","extension"=>[".car"]),
Array("name"=>"CURL Applet","mime"=>"application/vnd.curl.pcurl","extension"=>[".pcurl"]),
Array("name"=>"CustomMenu","mime"=>"application/vnd.yellowriver-custom-menu","extension"=>[".cmp"]),
Array("name"=>"Data Structure for the Security Suitability of Cryptographic Algorithms","mime"=>"application/dssc+der","extension"=>[".dssc"]),
Array("name"=>"Data Structure for the Security Suitability of Cryptographic Algorithms","mime"=>"application/dssc+xml","extension"=>[".xdssc"]),
Array("name"=>"Debian Package","mime"=>"application/x-debian-package","extension"=>[".deb"]),
Array("name"=>"DECE Audio","mime"=>"audio/vnd.dece.audio","extension"=>[".uva"]),
Array("name"=>"DECE Graphic","mime"=>"image/vnd.dece.graphic","extension"=>[".uvi"]),
Array("name"=>"DECE High Definition Video","mime"=>"video/vnd.dece.hd","extension"=>[".uvh"]),
Array("name"=>"DECE Mobile Video","mime"=>"video/vnd.dece.mobile","extension"=>[".uvm"]),
Array("name"=>"DECE MP4","mime"=>"video/vnd.uvvu.mp4","extension"=>[".uvu"]),
Array("name"=>"DECE PD Video","mime"=>"video/vnd.dece.pd","extension"=>[".uvp"]),
Array("name"=>"DECE SD Video","mime"=>"video/vnd.dece.sd","extension"=>[".uvs"]),
Array("name"=>"DECE Video","mime"=>"video/vnd.dece.video","extension"=>[".uvv"]),
Array("name"=>"Device Independent File Format (DVI)","mime"=>"application/x-dvi","extension"=>[".dvi"]),
Array("name"=>"Digital Siesmograph Networks - SEED Datafiles","mime"=>"application/vnd.fdsn.seed","extension"=>[".seed"]),
Array("name"=>"Digital Talking Book","mime"=>"application/x-dtbook+xml","extension"=>[".dtb"]),
Array("name"=>"Digital Talking Book - Resource File","mime"=>"application/x-dtbresource+xml","extension"=>[".res"]),
Array("name"=>"Digital Video Broadcasting","mime"=>"application/vnd.dvb.ait","extension"=>[".ait"]),
Array("name"=>"Digital Video Broadcasting","mime"=>"application/vnd.dvb.service","extension"=>[".svc"]),
Array("name"=>"Digital Winds Music","mime"=>"audio/vnd.digital-winds","extension"=>[".eol"]),
Array("name"=>"DjVu","mime"=>"image/vnd.djvu","extension"=>[".djvu"]),
Array("name"=>"Document Type Definition","mime"=>"application/xml-dtd","extension"=>[".dtd"]),
Array("name"=>"Dolby Meridian Lossless Packing","mime"=>"application/vnd.dolby.mlp","extension"=>[".mlp"]),
Array("name"=>"Doom Video Game","mime"=>"application/x-doom","extension"=>[".wad"]),
Array("name"=>"DPGraph","mime"=>"application/vnd.dpgraph","extension"=>[".dpg"]),
Array("name"=>"DRA Audio","mime"=>"audio/vnd.dra","extension"=>[".dra"]),
Array("name"=>"DreamFactory","mime"=>"application/vnd.dreamfactory","extension"=>[".dfac"]),
Array("name"=>"DTS Audio","mime"=>"audio/vnd.dts","extension"=>[".dts"]),
Array("name"=>"DTS High Definition Audio","mime"=>"audio/vnd.dts.hd","extension"=>[".dtshd"]),
Array("name"=>"DWG Drawing","mime"=>"image/vnd.dwg","extension"=>[".dwg"]),
Array("name"=>"DynaGeo","mime"=>"application/vnd.dynageo","extension"=>[".geo"]),
Array("name"=>"ECMAScript","mime"=>"application/ecmascript","extension"=>[".es"]),
Array("name"=>"EcoWin Chart","mime"=>"application/vnd.ecowin.chart","extension"=>[".mag"]),
Array("name"=>"EDMICS 2000","mime"=>"image/vnd.fujixerox.edmics-mmr","extension"=>[".mmr"]),
Array("name"=>"EDMICS 2000","mime"=>"image/vnd.fujixerox.edmics-rlc","extension"=>[".rlc"]),
Array("name"=>"Efficient XML Interchange","mime"=>"application/exi","extension"=>[".exi"]),
Array("name"=>"EFI Proteus","mime"=>"application/vnd.proteus.magazine","extension"=>[".mgz"]),
Array("name"=>"Electronic Publication","mime"=>"application/epub+zip","extension"=>[".epub"]),
Array("name"=>"Email Message","mime"=>"message/rfc822","extension"=>[".eml"]),
Array("name"=>"Enliven Viewer","mime"=>"application/vnd.enliven","extension"=>[".nml"]),
Array("name"=>"Express by Infoseek","mime"=>"application/vnd.is-xpr","extension"=>[".xpr"]),
Array("name"=>"eXtended Image File Format (XIFF)","mime"=>"image/vnd.xiff","extension"=>[".xif"]),
Array("name"=>"Extensible Forms Description Language","mime"=>"application/vnd.xfdl","extension"=>[".xfdl"]),
Array("name"=>"Extensible MultiModal Annotation","mime"=>"application/emma+xml","extension"=>[".emma"]),
Array("name"=>"EZPix Secure Photo Album","mime"=>"application/vnd.ezpix-album","extension"=>[".ez2"]),
Array("name"=>"EZPix Secure Photo Album","mime"=>"application/vnd.ezpix-package","extension"=>[".ez3"]),
Array("name"=>"FAST Search & Transfer ASA","mime"=>"image/vnd.fst","extension"=>[".fst"]),
Array("name"=>"FAST Search & Transfer ASA","mime"=>"video/vnd.fvt","extension"=>[".fvt"]),
Array("name"=>"FastBid Sheet","mime"=>"image/vnd.fastbidsheet","extension"=>[".fbs"]),
Array("name"=>"FCS Express Layout Link","mime"=>"application/vnd.denovo.fcselayout-link","extension"=>[".fe_launch"]),
Array("name"=>"Flash Video","mime"=>"video/x-f4v","extension"=>[".f4v"]),
Array("name"=>"Flash Video","mime"=>"video/x-flv","extension"=>[".flv"]),
Array("name"=>"FlashPix","mime"=>"image/vnd.fpx","extension"=>[".fpx"]),
Array("name"=>"FlashPix","mime"=>"image/vnd.net-fpx","extension"=>[".npx"]),
Array("name"=>"FLEXSTOR","mime"=>"text/vnd.fmi.flexstor","extension"=>[".flx"]),
Array("name"=>"FLI/FLC Animation Format","mime"=>"video/x-fli","extension"=>[".fli"]),
Array("name"=>"FluxTime Clip","mime"=>"application/vnd.fluxtime.clip","extension"=>[".ftc"]),
Array("name"=>"Forms Data Format","mime"=>"application/vnd.fdf","extension"=>[".fdf"]),
Array("name"=>"Fortran Source File","mime"=>"text/x-fortran","extension"=>[".f"]),
Array("name"=>"FrameMaker Interchange Format","mime"=>"application/vnd.mif","extension"=>[".mif"]),
Array("name"=>"FrameMaker Normal Format","mime"=>"application/vnd.framemaker","extension"=>[".fm"]),
Array("name"=>"FreeHand MX","mime"=>"image/x-freehand","extension"=>[".fh"]),
Array("name"=>"Friendly Software Corporation","mime"=>"application/vnd.fsc.weblaunch","extension"=>[".fsc"]),
Array("name"=>"Frogans Player","mime"=>"application/vnd.frogans.fnc","extension"=>[".fnc"]),
Array("name"=>"Frogans Player","mime"=>"application/vnd.frogans.ltf","extension"=>[".ltf"]),
Array("name"=>"Fujitsu - Xerox 2D CAD Data","mime"=>"application/vnd.fujixerox.ddd","extension"=>[".ddd"]),
Array("name"=>"Fujitsu - Xerox DocuWorks","mime"=>"application/vnd.fujixerox.docuworks","extension"=>[".xdw"]),
Array("name"=>"Fujitsu - Xerox DocuWorks Binder","mime"=>"application/vnd.fujixerox.docuworks.binder","extension"=>[".xbd"]),
Array("name"=>"Fujitsu Oasys","mime"=>"application/vnd.fujitsu.oasys","extension"=>[".oas"]),
Array("name"=>"Fujitsu Oasys","mime"=>"application/vnd.fujitsu.oasys2","extension"=>[".oa2"]),
Array("name"=>"Fujitsu Oasys","mime"=>"application/vnd.fujitsu.oasys3","extension"=>[".oa3"]),
Array("name"=>"Fujitsu Oasys","mime"=>"application/vnd.fujitsu.oasysgp","extension"=>[".fg5"]),
Array("name"=>"Fujitsu Oasys","mime"=>"application/vnd.fujitsu.oasysprs","extension"=>[".bh2"]),
Array("name"=>"FutureSplash Animator","mime"=>"application/x-futuresplash","extension"=>[".spl"]),
Array("name"=>"FuzzySheet","mime"=>"application/vnd.fuzzysheet","extension"=>[".fzs"]),
Array("name"=>"G3 Fax Image","mime"=>"image/g3fax","extension"=>[".g3"]),
Array("name"=>"GameMaker ActiveX","mime"=>"application/vnd.gmx","extension"=>[".gmx"]),
Array("name"=>"Gen-Trix Studio","mime"=>"model/vnd.gtw","extension"=>[".gtw"]),
Array("name"=>"Genomatix Tuxedo Framework","mime"=>"application/vnd.genomatix.tuxedo","extension"=>[".txd"]),
Array("name"=>"GeoGebra","mime"=>"application/vnd.geogebra.file","extension"=>[".ggb"]),
Array("name"=>"GeoGebra","mime"=>"application/vnd.geogebra.tool","extension"=>[".ggt"]),
Array("name"=>"Geometric Description Language (GDL)","mime"=>"model/vnd.gdl","extension"=>[".gdl"]),
Array("name"=>"GeoMetry Explorer","mime"=>"application/vnd.geometry-explorer","extension"=>[".gex"]),
Array("name"=>"GEONExT and JSXGraph","mime"=>"application/vnd.geonext","extension"=>[".gxt"]),
Array("name"=>"GeoplanW","mime"=>"application/vnd.geoplan","extension"=>[".g2w"]),
Array("name"=>"GeospacW","mime"=>"application/vnd.geospace","extension"=>[".g3w"]),
Array("name"=>"Ghostscript Font","mime"=>"application/x-font-ghostscript","extension"=>[".gsf"]),
Array("name"=>"Glyph Bitmap Distribution Format","mime"=>"application/x-font-bdf","extension"=>[".bdf"]),
Array("name"=>"GNU Tar Files","mime"=>"application/x-gtar","extension"=>[".gtar"]),
Array("name"=>"GNU Texinfo Document","mime"=>"application/x-texinfo","extension"=>[".texinfo"]),
Array("name"=>"Gnumeric","mime"=>"application/x-gnumeric","extension"=>[".gnumeric"]),
Array("name"=>"Google Earth - KML","mime"=>"application/vnd.google-earth.kml+xml","extension"=>[".kml"]),
Array("name"=>"Google Earth - Zipped KML","mime"=>"application/vnd.google-earth.kmz","extension"=>[".kmz"]),
Array("name"=>"GPS eXchange Format","mime"=>"application/gpx+xml","extension"=>[".gpx"]),
Array("name"=>"GrafEq","mime"=>"application/vnd.grafeq","extension"=>[".gqf"]),
Array("name"=>"Graphics Interchange Format","mime"=>"image/gif","extension"=>[".gif"]),
Array("name"=>"Graphviz","mime"=>"text/vnd.graphviz","extension"=>[".gv"]),
Array("name"=>"Groove - Account","mime"=>"application/vnd.groove-account","extension"=>[".gac"]),
Array("name"=>"Groove - Help","mime"=>"application/vnd.groove-help","extension"=>[".ghf"]),
Array("name"=>"Groove - Identity Message","mime"=>"application/vnd.groove-identity-message","extension"=>[".gim"]),
Array("name"=>"Groove - Injector","mime"=>"application/vnd.groove-injector","extension"=>[".grv"]),
Array("name"=>"Groove - Tool Message","mime"=>"application/vnd.groove-tool-message","extension"=>[".gtm"]),
Array("name"=>"Groove - Tool Template","mime"=>"application/vnd.groove-tool-template","extension"=>[".tpl"]),
Array("name"=>"Groove - Vcard","mime"=>"application/vnd.groove-vcard","extension"=>[".vcg"]),
Array("name"=>"GZip","mime"=>"application/gzip","extension"=>[".gz"]),
Array("name"=>"H.261","mime"=>"video/h261","extension"=>[".h261"]),
Array("name"=>"H.263","mime"=>"video/h263","extension"=>[".h263"]),
Array("name"=>"H.264","mime"=>"video/h264","extension"=>[".h264"]),
Array("name"=>"Hewlett Packard Instant Delivery","mime"=>"application/vnd.hp-hpid","extension"=>[".hpid"]),
Array("name"=>"Hewlett-Packard's WebPrintSmart","mime"=>"application/vnd.hp-hps","extension"=>[".hps"]),
Array("name"=>"Hierarchical Data Format","mime"=>"application/x-hdf","extension"=>[".hdf"]),
Array("name"=>"Hit'n'Mix","mime"=>"audio/vnd.rip","extension"=>[".rip"]),
Array("name"=>"Homebanking Computer Interface (HBCI)","mime"=>"application/vnd.hbci","extension"=>[".hbci"]),
Array("name"=>"HP Indigo Digital Press - Job Layout Languate","mime"=>"application/vnd.hp-jlyt","extension"=>[".jlt"]),
Array("name"=>"HP Printer Command Language","mime"=>"application/vnd.hp-pcl","extension"=>[".pcl"]),
Array("name"=>"HP-GL/2 and HP RTL","mime"=>"application/vnd.hp-hpgl","extension"=>[".hpgl"]),
Array("name"=>"HV Script","mime"=>"application/vnd.yamaha.hv-script","extension"=>[".hvs"]),
Array("name"=>"HV Voice Dictionary","mime"=>"application/vnd.yamaha.hv-dic","extension"=>[".hvd"]),
Array("name"=>"HV Voice Parameter","mime"=>"application/vnd.yamaha.hv-voice","extension"=>[".hvp"]),
Array("name"=>"Hydrostatix Master Suite","mime"=>"application/vnd.hydrostatix.sof-data","extension"=>[".sfd-hdstx"]),
Array("name"=>"Hyperstudio","mime"=>"application/hyperstudio","extension"=>[".stk"]),
Array("name"=>"Hypertext Application Language","mime"=>"application/vnd.hal+xml","extension"=>[".hal"]),
Array("name"=>"HyperText Markup Language (HTML)","mime"=>"text/html","extension"=>[".html"]),
Array("name"=>"IBM DB2 Rights Manager","mime"=>"application/vnd.ibm.rights-management","extension"=>[".irm"]),
Array("name"=>"IBM Electronic Media Management System - Secure Container","mime"=>"application/vnd.ibm.secure-container","extension"=>[".sc"]),
Array("name"=>"iCalendar","mime"=>"text/calendar","extension"=>[".ics"]),
Array("name"=>"ICC profile","mime"=>"application/vnd.iccprofile","extension"=>[".icc"]),
Array("name"=>"Icon Image","mime"=>"image/x-icon","extension"=>[".ico"]),
Array("name"=>"igLoader","mime"=>"application/vnd.igloader","extension"=>[".igl"]),
Array("name"=>"Image Exchange Format","mime"=>"image/ief","extension"=>[".ief"]),
Array("name"=>"ImmerVision PURE Players","mime"=>"application/vnd.immervision-ivp","extension"=>[".ivp"]),
Array("name"=>"ImmerVision PURE Players","mime"=>"application/vnd.immervision-ivu","extension"=>[".ivu"]),
Array("name"=>"IMS Networks","mime"=>"application/reginfo+xml","extension"=>[".rif"]),
Array("name"=>"In3D - 3DML","mime"=>"text/vnd.in3d.3dml","extension"=>[".3dml"]),
Array("name"=>"In3D - 3DML","mime"=>"text/vnd.in3d.spot","extension"=>[".spot"]),
Array("name"=>"Initial Graphics Exchange Specification (IGES)","mime"=>"model/iges","extension"=>[".igs"]),
Array("name"=>"Interactive Geometry Software","mime"=>"application/vnd.intergeo","extension"=>[".i2g"]),
Array("name"=>"Interactive Geometry Software Cinderella","mime"=>"application/vnd.cinderella","extension"=>[".cdy"]),
Array("name"=>"Intercon FormNet","mime"=>"application/vnd.intercon.formnet","extension"=>[".xpw"]),
Array("name"=>"International Society for Advancement of Cytometry","mime"=>"application/vnd.isac.fcs","extension"=>[".fcs"]),
Array("name"=>"Internet Protocol Flow Information Export","mime"=>"application/ipfix","extension"=>[".ipfix"]),
Array("name"=>"Internet Public Key Infrastructure - Certificate","mime"=>"application/pkix-cert","extension"=>[".cer"]),
Array("name"=>"Internet Public Key Infrastructure - Certificate Management Protocole","mime"=>"application/pkixcmp","extension"=>[".pki"]),
Array("name"=>"Internet Public Key Infrastructure - Certificate Revocation Lists","mime"=>"application/pkix-crl","extension"=>[".crl"]),
Array("name"=>"Internet Public Key Infrastructure - Certification Path","mime"=>"application/pkix-pkipath","extension"=>[".pkipath"]),
Array("name"=>"IOCOM Visimeet","mime"=>"application/vnd.insors.igm","extension"=>[".igm"]),
Array("name"=>"IP Unplugged Roaming Client","mime"=>"application/vnd.ipunplugged.rcprofile","extension"=>[".rcprofile"]),
Array("name"=>"iRepository / Lucidoc Editor","mime"=>"application/vnd.irepository.package+xml","extension"=>[".irp"]),
Array("name"=>"J2ME App Descriptor","mime"=>"text/vnd.sun.j2me.app-descriptor","extension"=>[".jad"]),
Array("name"=>"Java Archive","mime"=>"application/java-archive","extension"=>[".jar"]),
Array("name"=>"Java Bytecode File","mime"=>"application/java-vm","extension"=>[".class"]),
Array("name"=>"Java Network Launching Protocol","mime"=>"application/x-java-jnlp-file","extension"=>[".jnlp"]),
Array("name"=>"Java Serialized Object","mime"=>"application/java-serialized-object","extension"=>[".ser"]),
Array("name"=>"Java Source File","mime"=>"text/x-java-source,java","extension"=>[".java"]),
Array("name"=>"JavaScript","mime"=>"application/javascript","extension"=>[".js"]),
Array("name"=>"JavaScript Module","mime"=>"text/javascript","extension"=>[".mjs"]),
Array("name"=>"JavaScript Module","mime"=>"text/javascript","extension"=>[".mjs"]),
Array("name"=>"JavaScript Object Notation (JSON)","mime"=>"application/json","extension"=>[".json"]),
Array("name"=>"Joda Archive","mime"=>"application/vnd.joost.joda-archive","extension"=>[".joda"]),
Array("name"=>"JPEG 2000 Compound Image File Format","mime"=>"video/jpm","extension"=>[".jpm"]),
Array("name"=>"JPEG Image","mime"=>"image/jpeg","extension"=>[".jpeg",".jpg"]),
Array("name"=>"JPEG Image (Citrix client)","mime"=>"image/x-citrix-jpeg","extension"=>[".jpeg",".jpg"]),
Array("name"=>"JPEG Image (Progressive)","mime"=>"image/pjpeg","extension"=>[".pjpeg"]),
Array("name"=>"JPGVideo","mime"=>"video/jpeg","extension"=>[".jpgv"]),
Array("name"=>"JSON - Linked Data","mime"=>"application/ld+json","extension"=>[".jsonld"]),
Array("name"=>"Kahootz","mime"=>"application/vnd.kahootz","extension"=>[".ktz"]),
Array("name"=>"Karaoke on Chipnuts Chipsets","mime"=>"application/vnd.chipnuts.karaoke-mmd","extension"=>[".mmd"]),
Array("name"=>"KDE KOffice Office Suite - Karbon","mime"=>"application/vnd.kde.karbon","extension"=>[".karbon"]),
Array("name"=>"KDE KOffice Office Suite - KChart","mime"=>"application/vnd.kde.kchart","extension"=>[".chrt"]),
Array("name"=>"KDE KOffice Office Suite - Kformula","mime"=>"application/vnd.kde.kformula","extension"=>[".kfo"]),
Array("name"=>"KDE KOffice Office Suite - Kivio","mime"=>"application/vnd.kde.kivio","extension"=>[".flw"]),
Array("name"=>"KDE KOffice Office Suite - Kontour","mime"=>"application/vnd.kde.kontour","extension"=>[".kon"]),
Array("name"=>"KDE KOffice Office Suite - Kpresenter","mime"=>"application/vnd.kde.kpresenter","extension"=>[".kpr"]),
Array("name"=>"KDE KOffice Office Suite - Kspread","mime"=>"application/vnd.kde.kspread","extension"=>[".ksp"]),
Array("name"=>"KDE KOffice Office Suite - Kword","mime"=>"application/vnd.kde.kword","extension"=>[".kwd"]),
Array("name"=>"Kenamea App","mime"=>"application/vnd.kenameaapp","extension"=>[".htke"]),
Array("name"=>"Kidspiration","mime"=>"application/vnd.kidspiration","extension"=>[".kia"]),
Array("name"=>"Kinar Applications","mime"=>"application/vnd.kinar","extension"=>[".kne"]),
Array("name"=>"Kodak Storyshare","mime"=>"application/vnd.kodak-descriptor","extension"=>[".sse"]),
Array("name"=>"Laser App Enterprise","mime"=>"application/vnd.las.las+xml","extension"=>[".lasxml"]),
Array("name"=>"LaTeX","mime"=>"application/x-latex","extension"=>[".latex"]),
Array("name"=>"Life Balance - Desktop Edition","mime"=>"application/vnd.llamagraphics.life-balance.desktop","extension"=>[".lbd"]),
Array("name"=>"Life Balance - Exchange Format","mime"=>"application/vnd.llamagraphics.life-balance.exchange+xml","extension"=>[".lbe"]),
Array("name"=>"Lightspeed Audio Lab","mime"=>"application/vnd.jam","extension"=>[".jam"]),
Array("name"=>"Lotus 1-2-3","mime"=>"application/vnd.lotus-1-2-3","extension"=>[".123"]),
Array("name"=>"Lotus Approach","mime"=>"application/vnd.lotus-approach","extension"=>[".apr"]),
Array("name"=>"Lotus Freelance","mime"=>"application/vnd.lotus-freelance","extension"=>[".pre"]),
Array("name"=>"Lotus Notes","mime"=>"application/vnd.lotus-notes","extension"=>[".nsf"]),
Array("name"=>"Lotus Organizer","mime"=>"application/vnd.lotus-organizer","extension"=>[".org"]),
Array("name"=>"Lotus Screencam","mime"=>"application/vnd.lotus-screencam","extension"=>[".scm"]),
Array("name"=>"Lotus Wordpro","mime"=>"application/vnd.lotus-wordpro","extension"=>[".lwp"]),
Array("name"=>"Lucent Voice","mime"=>"audio/vnd.lucent.voice","extension"=>[".lvp"]),
Array("name"=>"M3U (Multimedia Playlist)","mime"=>"audio/x-mpegurl","extension"=>[".m3u"]),
Array("name"=>"M4v","mime"=>"video/x-m4v","extension"=>[".m4v"]),
Array("name"=>"Macintosh BinHex 4.0","mime"=>"application/mac-binhex40","extension"=>[".hqx"]),
Array("name"=>"MacPorts Port System","mime"=>"application/vnd.macports.portpkg","extension"=>[".portpkg"]),
Array("name"=>"MapGuide DBXML","mime"=>"application/vnd.osgeo.mapguide.package","extension"=>[".mgp"]),
Array("name"=>"MARC Formats","mime"=>"application/marc","extension"=>[".mrc"]),
Array("name"=>"MARC21 XML Schema","mime"=>"application/marcxml+xml","extension"=>[".mrcx"]),
Array("name"=>"Material Exchange Format","mime"=>"application/mxf","extension"=>[".mxf"]),
Array("name"=>"Mathematica Notebook Player","mime"=>"application/vnd.wolfram.player","extension"=>[".nbp"]),
Array("name"=>"Mathematica Notebooks","mime"=>"application/mathematica","extension"=>[".ma"]),
Array("name"=>"Mathematical Markup Language","mime"=>"application/mathml+xml","extension"=>[".mathml"]),
Array("name"=>"Mbox database files","mime"=>"application/mbox","extension"=>[".mbox"]),
Array("name"=>"MedCalc","mime"=>"application/vnd.medcalcdata","extension"=>[".mc1"]),
Array("name"=>"Media Server Control Markup Language","mime"=>"application/mediaservercontrol+xml","extension"=>[".mscml"]),
Array("name"=>"MediaRemote","mime"=>"application/vnd.mediastation.cdkey","extension"=>[".cdkey"]),
Array("name"=>"Medical Waveform Encoding Format","mime"=>"application/vnd.mfer","extension"=>[".mwf"]),
Array("name"=>"Melody Format for Mobile Platform","mime"=>"application/vnd.mfmp","extension"=>[".mfm"]),
Array("name"=>"Mesh Data Type","mime"=>"model/mesh","extension"=>[".msh"]),
Array("name"=>"Metadata Authority Description Schema","mime"=>"application/mads+xml","extension"=>[".mads"]),
Array("name"=>"Metadata Encoding and Transmission Standard","mime"=>"application/mets+xml","extension"=>[".mets"]),
Array("name"=>"Metadata Object Description Schema","mime"=>"application/mods+xml","extension"=>[".mods"]),
Array("name"=>"Metalink","mime"=>"application/metalink4+xml","extension"=>[".meta4"]),
Array("name"=>"Micro CADAM Helix D&D","mime"=>"application/vnd.mcd","extension"=>[".mcd"]),
Array("name"=>"Micrografx","mime"=>"application/vnd.micrografx.flo","extension"=>[".flo"]),
Array("name"=>"Micrografx iGrafx Professional","mime"=>"application/vnd.micrografx.igx","extension"=>[".igx"]),
Array("name"=>"MICROSEC e-Szign�","mime"=>"application/vnd.eszigno3+xml","extension"=>[".es3"]),
Array("name"=>"Microsoft Access","mime"=>"application/x-msaccess","extension"=>[".mdb"]),
Array("name"=>"Microsoft Advanced Systems Format (ASF)","mime"=>"video/x-ms-asf","extension"=>[".asf"]),
Array("name"=>"Microsoft Application","mime"=>"application/x-msdownload","extension"=>[".exe"]),
Array("name"=>"Microsoft Artgalry","mime"=>"application/vnd.ms-artgalry","extension"=>[".cil"]),
Array("name"=>"Microsoft Cabinet File","mime"=>"application/vnd.ms-cab-compressed","extension"=>[".cab"]),
Array("name"=>"Microsoft Class Server","mime"=>"application/vnd.ms-ims","extension"=>[".ims"]),
Array("name"=>"Microsoft ClickOnce","mime"=>"application/x-ms-application","extension"=>[".application"]),
Array("name"=>"Microsoft Clipboard Clip","mime"=>"application/x-msclip","extension"=>[".clp"]),
Array("name"=>"Microsoft Document Imaging Format","mime"=>"image/vnd.ms-modi","extension"=>[".mdi"]),
Array("name"=>"Microsoft Embedded OpenType","mime"=>"application/vnd.ms-fontobject","extension"=>[".eot"]),
Array("name"=>"Microsoft Excel","mime"=>"application/vnd.ms-excel","extension"=>[".xls"]),
Array("name"=>"Microsoft Excel - Add-In File","mime"=>"application/vnd.ms-excel.addin.macroenabled.12","extension"=>[".xlam"]),
Array("name"=>"Microsoft Excel - Binary Workbook","mime"=>"application/vnd.ms-excel.sheet.binary.macroenabled.12","extension"=>[".xlsb"]),
Array("name"=>"Microsoft Excel - Macro-Enabled Template File","mime"=>"application/vnd.ms-excel.template.macroenabled.12","extension"=>[".xltm"]),
Array("name"=>"Microsoft Excel - Macro-Enabled Workbook","mime"=>"application/vnd.ms-excel.sheet.macroenabled.12","extension"=>[".xlsm"]),
Array("name"=>"Microsoft Html Help File","mime"=>"application/vnd.ms-htmlhelp","extension"=>[".chm"]),
Array("name"=>"Microsoft Information Card","mime"=>"application/x-mscardfile","extension"=>[".crd"]),
Array("name"=>"Microsoft Learning Resource Module","mime"=>"application/vnd.ms-lrm","extension"=>[".lrm"]),
Array("name"=>"Microsoft MediaView","mime"=>"application/x-msmediaview","extension"=>[".mvb"]),
Array("name"=>"Microsoft Money","mime"=>"application/x-msmoney","extension"=>[".mny"]),
Array("name"=>"Microsoft Office - OOXML - Presentation","mime"=>"application/vnd.openxmlformats-officedocument.presentationml.presentation","extension"=>[".pptx"]),
Array("name"=>"Microsoft Office - OOXML - Presentation (Slide)","mime"=>"application/vnd.openxmlformats-officedocument.presentationml.slide","extension"=>[".sldx"]),
Array("name"=>"Microsoft Office - OOXML - Presentation (Slideshow)","mime"=>"application/vnd.openxmlformats-officedocument.presentationml.slideshow","extension"=>[".ppsx"]),
Array("name"=>"Microsoft Office - OOXML - Presentation Template","mime"=>"application/vnd.openxmlformats-officedocument.presentationml.template","extension"=>[".potx"]),
Array("name"=>"Microsoft Office - OOXML - Spreadsheet","mime"=>"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","extension"=>[".xlsx"]),
Array("name"=>"Microsoft Office - OOXML - Spreadsheet Template","mime"=>"application/vnd.openxmlformats-officedocument.spreadsheetml.template","extension"=>[".xltx"]),
Array("name"=>"Microsoft Office - OOXML - Word Document","mime"=>"application/vnd.openxmlformats-officedocument.wordprocessingml.document","extension"=>[".docx"]),
Array("name"=>"Microsoft Office - OOXML - Word Document Template","mime"=>"application/vnd.openxmlformats-officedocument.wordprocessingml.template","extension"=>[".dotx"]),
Array("name"=>"Microsoft Office Binder","mime"=>"application/x-msbinder","extension"=>[".obd"]),
Array("name"=>"Microsoft Office System Release Theme","mime"=>"application/vnd.ms-officetheme","extension"=>[".thmx"]),
Array("name"=>"Microsoft OneNote","mime"=>"application/onenote","extension"=>[".onetoc"]),
Array("name"=>"Microsoft PlayReady Ecosystem","mime"=>"audio/vnd.ms-playready.media.pya","extension"=>[".pya"]),
Array("name"=>"Microsoft PlayReady Ecosystem Video","mime"=>"video/vnd.ms-playready.media.pyv","extension"=>[".pyv"]),
Array("name"=>"Microsoft PowerPoint","mime"=>"application/vnd.ms-powerpoint","extension"=>[".ppt"]),
Array("name"=>"Microsoft PowerPoint - Add-in file","mime"=>"application/vnd.ms-powerpoint.addin.macroenabled.12","extension"=>[".ppam"]),
Array("name"=>"Microsoft PowerPoint - Macro-Enabled Open XML Slide","mime"=>"application/vnd.ms-powerpoint.slide.macroenabled.12","extension"=>[".sldm"]),
Array("name"=>"Microsoft PowerPoint - Macro-Enabled Presentation File","mime"=>"application/vnd.ms-powerpoint.presentation.macroenabled.12","extension"=>[".pptm"]),
Array("name"=>"Microsoft PowerPoint - Macro-Enabled Slide Show File","mime"=>"application/vnd.ms-powerpoint.slideshow.macroenabled.12","extension"=>[".ppsm"]),
Array("name"=>"Microsoft PowerPoint - Macro-Enabled Template File","mime"=>"application/vnd.ms-powerpoint.template.macroenabled.12","extension"=>[".potm"]),
Array("name"=>"Microsoft Project","mime"=>"application/vnd.ms-project","extension"=>[".mpp"]),
Array("name"=>"Microsoft Publisher","mime"=>"application/x-mspublisher","extension"=>[".pub"]),
Array("name"=>"Microsoft Schedule+","mime"=>"application/x-msschedule","extension"=>[".scd"]),
Array("name"=>"Microsoft Silverlight","mime"=>"application/x-silverlight-app","extension"=>[".xap"]),
Array("name"=>"Microsoft Trust UI Provider - Certificate Trust Link","mime"=>"application/vnd.ms-pki.stl","extension"=>[".stl"]),
Array("name"=>"Microsoft Trust UI Provider - Security Catalog","mime"=>"application/vnd.ms-pki.seccat","extension"=>[".cat"]),
Array("name"=>"Microsoft Visio","mime"=>"application/vnd.visio","extension"=>[".vsd"]),
Array("name"=>"Microsoft Visio 2013","mime"=>"application/vnd.visio2013","extension"=>[".vsdx"]),
Array("name"=>"Microsoft Windows Media","mime"=>"video/x-ms-wm","extension"=>[".wm"]),
Array("name"=>"Microsoft Windows Media Audio","mime"=>"audio/x-ms-wma","extension"=>[".wma"]),
Array("name"=>"Microsoft Windows Media Audio Redirector","mime"=>"audio/x-ms-wax","extension"=>[".wax"]),
Array("name"=>"Microsoft Windows Media Audio/Video Playlist","mime"=>"video/x-ms-wmx","extension"=>[".wmx"]),
Array("name"=>"Microsoft Windows Media Player Download Package","mime"=>"application/x-ms-wmd","extension"=>[".wmd"]),
Array("name"=>"Microsoft Windows Media Player Playlist","mime"=>"application/vnd.ms-wpl","extension"=>[".wpl"]),
Array("name"=>"Microsoft Windows Media Player Skin Package","mime"=>"application/x-ms-wmz","extension"=>[".wmz"]),
Array("name"=>"Microsoft Windows Media Video","mime"=>"video/x-ms-wmv","extension"=>[".wmv"]),
Array("name"=>"Microsoft Windows Media Video Playlist","mime"=>"video/x-ms-wvx","extension"=>[".wvx"]),
Array("name"=>"Microsoft Windows Metafile","mime"=>"application/x-msmetafile","extension"=>[".wmf"]),
Array("name"=>"Microsoft Windows Terminal Services","mime"=>"application/x-msterminal","extension"=>[".trm"]),
Array("name"=>"Microsoft Word","mime"=>"application/msword","extension"=>[".doc"]),
Array("name"=>"Microsoft Word - Macro-Enabled Document","mime"=>"application/vnd.ms-word.document.macroenabled.12","extension"=>[".docm"]),
Array("name"=>"Microsoft Word - Macro-Enabled Template","mime"=>"application/vnd.ms-word.template.macroenabled.12","extension"=>[".dotm"]),
Array("name"=>"Microsoft Wordpad","mime"=>"application/x-mswrite","extension"=>[".wri"]),
Array("name"=>"Microsoft Works","mime"=>"application/vnd.ms-works","extension"=>[".wps"]),
Array("name"=>"Microsoft XAML Browser Application","mime"=>"application/x-ms-xbap","extension"=>[".xbap"]),
Array("name"=>"Microsoft XML Paper Specification","mime"=>"application/vnd.ms-xpsdocument","extension"=>[".xps"]),
Array("name"=>"MIDI","mime"=>"audio/midi","extension"=>[".midi"]),
Array("name"=>"MIDI - Musical Instrument Digital Interface","mime"=>"audio/midi","extension"=>[".mid"]),
Array("name"=>"MiniPay","mime"=>"application/vnd.ibm.minipay","extension"=>[".mpy"]),
Array("name"=>"MO=>DCA-P","mime"=>"application/vnd.ibm.modcap","extension"=>[".afp"]),
Array("name"=>"Mobile Information Device Profile","mime"=>"application/vnd.jcp.javame.midlet-rms","extension"=>[".rms"]),
Array("name"=>"MobileTV","mime"=>"application/vnd.tmobile-livetv","extension"=>[".tmo"]),
Array("name"=>"Mobipocket","mime"=>"application/x-mobipocket-ebook","extension"=>[".prc"]),
Array("name"=>"Mobius Management Systems - Basket file","mime"=>"application/vnd.mobius.mbk","extension"=>[".mbk"]),
Array("name"=>"Mobius Management Systems - Distribution Database","mime"=>"application/vnd.mobius.dis","extension"=>[".dis"]),
Array("name"=>"Mobius Management Systems - Policy Definition Language File","mime"=>"application/vnd.mobius.plc","extension"=>[".plc"]),
Array("name"=>"Mobius Management Systems - Query File","mime"=>"application/vnd.mobius.mqy","extension"=>[".mqy"]),
Array("name"=>"Mobius Management Systems - Script Language","mime"=>"application/vnd.mobius.msl","extension"=>[".msl"]),
Array("name"=>"Mobius Management Systems - Topic Index File","mime"=>"application/vnd.mobius.txf","extension"=>[".txf"]),
Array("name"=>"Mobius Management Systems - UniversalArchive","mime"=>"application/vnd.mobius.daf","extension"=>[".daf"]),
Array("name"=>"mod_fly / fly.cgi","mime"=>"text/vnd.fly","extension"=>[".fly"]),
Array("name"=>"Mophun Certificate","mime"=>"application/vnd.mophun.certificate","extension"=>[".mpc"]),
Array("name"=>"Mophun VM","mime"=>"application/vnd.mophun.application","extension"=>[".mpn"]),
Array("name"=>"Motion JPEG 2000","mime"=>"video/mj2","extension"=>[".mj2"]),
Array("name"=>"MPEG Audio","mime"=>"audio/mpeg","extension"=>[".mpga"]),
Array("name"=>"MPEG Transport Stream","mime"=>"video/mp2t","extension"=>[".ts"]),
Array("name"=>"MPEG Url","mime"=>"video/vnd.mpegurl","extension"=>[".mxu"]),
Array("name"=>"MPEG Video","mime"=>"video/mpeg","extension"=>[".mpeg"]),
Array("name"=>"MPEG-21","mime"=>"application/mp21","extension"=>[".m21"]),
Array("name"=>"MPEG-4 Audio","mime"=>"audio/mp4","extension"=>[".mp4a"]),
Array("name"=>"MPEG-4 Video","mime"=>"video/mp4","extension"=>[".mp4"]),
Array("name"=>"MPEG4","mime"=>"application/mp4","extension"=>[".mp4"]),
Array("name"=>"Multimedia Playlist Unicode","mime"=>"application/vnd.apple.mpegurl","extension"=>[".m3u8"]),
Array("name"=>"MUsical Score Interpreted Code Invented for the ASCII designation of Notation","mime"=>"application/vnd.musician","extension"=>[".mus"]),
Array("name"=>"Muvee Automatic Video Editing","mime"=>"application/vnd.muvee.style","extension"=>[".msty"]),
Array("name"=>"MXML","mime"=>"application/xv+xml","extension"=>[".mxml"]),
Array("name"=>"N-Gage Game Data","mime"=>"application/vnd.nokia.n-gage.data","extension"=>[".ngdat"]),
Array("name"=>"N-Gage Game Installer","mime"=>"application/vnd.nokia.n-gage.symbian.install","extension"=>[".n-gage"]),
Array("name"=>"Navigation Control file for XML (for ePub)","mime"=>"application/x-dtbncx+xml","extension"=>[".ncx"]),
Array("name"=>"Network Common Data Form (NetCDF)","mime"=>"application/x-netcdf","extension"=>[".nc"]),
Array("name"=>"neuroLanguage","mime"=>"application/vnd.neurolanguage.nlu","extension"=>[".nlu"]),
Array("name"=>"New Moon Liftoff/DNA","mime"=>"application/vnd.dna","extension"=>[".dna"]),
Array("name"=>"NobleNet Directory","mime"=>"application/vnd.noblenet-directory","extension"=>[".nnd"]),
Array("name"=>"NobleNet Sealer","mime"=>"application/vnd.noblenet-sealer","extension"=>[".nns"]),
Array("name"=>"NobleNet Web","mime"=>"application/vnd.noblenet-web","extension"=>[".nnw"]),
Array("name"=>"Nokia Radio Application - Preset","mime"=>"application/vnd.nokia.radio-preset","extension"=>[".rpst"]),
Array("name"=>"Nokia Radio Application - Preset","mime"=>"application/vnd.nokia.radio-presets","extension"=>[".rpss"]),
Array("name"=>"Notation3","mime"=>"text/n3","extension"=>[".n3"]),
Array("name"=>"Novadigm's RADIA and EDM products","mime"=>"application/vnd.novadigm.edm","extension"=>[".edm"]),
Array("name"=>"Novadigm's RADIA and EDM products","mime"=>"application/vnd.novadigm.edx","extension"=>[".edx"]),
Array("name"=>"Novadigm's RADIA and EDM products","mime"=>"application/vnd.novadigm.ext","extension"=>[".ext"]),
Array("name"=>"NpGraphIt","mime"=>"application/vnd.flographit","extension"=>[".gph"]),
Array("name"=>"Nuera ECELP 4800","mime"=>"audio/vnd.nuera.ecelp4800","extension"=>[".ecelp4800"]),
Array("name"=>"Nuera ECELP 7470","mime"=>"audio/vnd.nuera.ecelp7470","extension"=>[".ecelp7470"]),
Array("name"=>"Nuera ECELP 9600","mime"=>"audio/vnd.nuera.ecelp9600","extension"=>[".ecelp9600"]),
Array("name"=>"Office Document Architecture","mime"=>"application/oda","extension"=>[".oda"]),
Array("name"=>"Ogg","mime"=>"application/ogg","extension"=>[".ogx"]),
Array("name"=>"Ogg Audio","mime"=>"audio/ogg","extension"=>[".oga"]),
Array("name"=>"Ogg Video","mime"=>"video/ogg","extension"=>[".ogv"]),
Array("name"=>"OMA Download Agents","mime"=>"application/vnd.oma.dd2+xml","extension"=>[".dd2"]),
Array("name"=>"Open Document Text Web","mime"=>"application/vnd.oasis.opendocument.text-web","extension"=>[".oth"]),
Array("name"=>"Open eBook Publication Structure","mime"=>"application/oebps-package+xml","extension"=>[".opf"]),
Array("name"=>"Open Financial Exchange","mime"=>"application/vnd.intu.qbo","extension"=>[".qbo"]),
Array("name"=>"Open Office Extension","mime"=>"application/vnd.openofficeorg.extension","extension"=>[".oxt"]),
Array("name"=>"Open Score Format","mime"=>"application/vnd.yamaha.openscoreformat","extension"=>[".osf"]),
Array("name"=>"Open Web Media Project - Audio","mime"=>"audio/webm","extension"=>[".weba"]),
Array("name"=>"Open Web Media Project - Video","mime"=>"video/webm","extension"=>[".webm"]),
Array("name"=>"OpenDocument Chart","mime"=>"application/vnd.oasis.opendocument.chart","extension"=>[".odc"]),
Array("name"=>"OpenDocument Chart Template","mime"=>"application/vnd.oasis.opendocument.chart-template","extension"=>[".otc"]),
Array("name"=>"OpenDocument Database","mime"=>"application/vnd.oasis.opendocument.database","extension"=>[".odb"]),
Array("name"=>"OpenDocument Formula","mime"=>"application/vnd.oasis.opendocument.formula","extension"=>[".odf"]),
Array("name"=>"OpenDocument Formula Template","mime"=>"application/vnd.oasis.opendocument.formula-template","extension"=>[".odft"]),
Array("name"=>"OpenDocument Graphics","mime"=>"application/vnd.oasis.opendocument.graphics","extension"=>[".odg"]),
Array("name"=>"OpenDocument Graphics Template","mime"=>"application/vnd.oasis.opendocument.graphics-template","extension"=>[".otg"]),
Array("name"=>"OpenDocument Image","mime"=>"application/vnd.oasis.opendocument.image","extension"=>[".odi"]),
Array("name"=>"OpenDocument Image Template","mime"=>"application/vnd.oasis.opendocument.image-template","extension"=>[".oti"]),
Array("name"=>"OpenDocument Presentation","mime"=>"application/vnd.oasis.opendocument.presentation","extension"=>[".odp"]),
Array("name"=>"OpenDocument Presentation Template","mime"=>"application/vnd.oasis.opendocument.presentation-template","extension"=>[".otp"]),
Array("name"=>"OpenDocument Spreadsheet","mime"=>"application/vnd.oasis.opendocument.spreadsheet","extension"=>[".ods"]),
Array("name"=>"OpenDocument Spreadsheet Template","mime"=>"application/vnd.oasis.opendocument.spreadsheet-template","extension"=>[".ots"]),
Array("name"=>"OpenDocument Text","mime"=>"application/vnd.oasis.opendocument.text","extension"=>[".odt"]),
Array("name"=>"OpenDocument Text Master","mime"=>"application/vnd.oasis.opendocument.text-master","extension"=>[".odm"]),
Array("name"=>"OpenDocument Text Template","mime"=>"application/vnd.oasis.opendocument.text-template","extension"=>[".ott"]),
Array("name"=>"OpenGL Textures (KTX)","mime"=>"image/ktx","extension"=>[".ktx"]),
Array("name"=>"OpenOffice - Calc (Spreadsheet)","mime"=>"application/vnd.sun.xml.calc","extension"=>[".sxc"]),
Array("name"=>"OpenOffice - Calc Template (Spreadsheet)","mime"=>"application/vnd.sun.xml.calc.template","extension"=>[".stc"]),
Array("name"=>"OpenOffice - Draw (Graphics)","mime"=>"application/vnd.sun.xml.draw","extension"=>[".sxd"]),
Array("name"=>"OpenOffice - Draw Template (Graphics)","mime"=>"application/vnd.sun.xml.draw.template","extension"=>[".std"]),
Array("name"=>"OpenOffice - Impress (Presentation)","mime"=>"application/vnd.sun.xml.impress","extension"=>[".sxi"]),
Array("name"=>"OpenOffice - Impress Template (Presentation)","mime"=>"application/vnd.sun.xml.impress.template","extension"=>[".sti"]),
Array("name"=>"OpenOffice - Math (Formula)","mime"=>"application/vnd.sun.xml.math","extension"=>[".sxm"]),
Array("name"=>"OpenOffice - Writer (Text - HTML)","mime"=>"application/vnd.sun.xml.writer","extension"=>[".sxw"]),
Array("name"=>"OpenOffice - Writer (Text - HTML)","mime"=>"application/vnd.sun.xml.writer.global","extension"=>[".sxg"]),
Array("name"=>"OpenOffice - Writer Template (Text - HTML)","mime"=>"application/vnd.sun.xml.writer.template","extension"=>[".stw"]),
Array("name"=>"OpenType Font File","mime"=>"application/x-font-otf","extension"=>[".otf"]),
Array("name"=>"Opus Audio","mime"=>"audio/opus","extension"=>[".opus"]),
Array("name"=>"OSFPVG","mime"=>"application/vnd.yamaha.openscoreformat.osfpvg+xml","extension"=>[".osfpvg"]),
Array("name"=>"OSGi Deployment Package","mime"=>"application/vnd.osgi.dp","extension"=>[".dp"]),
Array("name"=>"PalmOS Data","mime"=>"application/vnd.palm","extension"=>[".pdb"]),
Array("name"=>"Pascal Source File","mime"=>"text/x-pascal","extension"=>[".p"]),
Array("name"=>"PawaaFILE","mime"=>"application/vnd.pawaafile","extension"=>[".paw"]),
Array("name"=>"PCL 6 Enhanced (Formely PCL XL)","mime"=>"application/vnd.hp-pclxl","extension"=>[".pclxl"]),
Array("name"=>"Pcsel eFIF File","mime"=>"application/vnd.picsel","extension"=>[".efif"]),
Array("name"=>"PCX Image","mime"=>"image/x-pcx","extension"=>[".pcx"]),
Array("name"=>"Photoshop Document","mime"=>"image/vnd.adobe.photoshop","extension"=>[".psd"]),
Array("name"=>"PICSRules","mime"=>"application/pics-rules","extension"=>[".prf"]),
Array("name"=>"PICT Image","mime"=>"image/x-pict","extension"=>[".pic"]),
Array("name"=>"pIRCh","mime"=>"application/x-chat","extension"=>[".chat"]),
Array("name"=>"PKCS #10 - Certification Request Standard","mime"=>"application/pkcs10","extension"=>[".p10"]),
Array("name"=>"PKCS #12 - Personal Information Exchange Syntax Standard","mime"=>"application/x-pkcs12","extension"=>[".p12"]),
Array("name"=>"PKCS #7 - Cryptographic Message Syntax Standard","mime"=>"application/pkcs7-mime","extension"=>[".p7m"]),
Array("name"=>"PKCS #7 - Cryptographic Message Syntax Standard","mime"=>"application/pkcs7-signature","extension"=>[".p7s"]),
Array("name"=>"PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)","mime"=>"application/x-pkcs7-certreqresp","extension"=>[".p7r"]),
Array("name"=>"PKCS #7 - Cryptographic Message Syntax Standard (Certificates)","mime"=>"application/x-pkcs7-certificates","extension"=>[".p7b"]),
Array("name"=>"PKCS #8 - Private-Key Information Syntax Standard","mime"=>"application/pkcs8","extension"=>[".p8"]),
Array("name"=>"PocketLearn Viewers","mime"=>"application/vnd.pocketlearn","extension"=>[".plf"]),
Array("name"=>"Portable Anymap Image","mime"=>"image/x-portable-anymap","extension"=>[".pnm"]),
Array("name"=>"Portable Bitmap Format","mime"=>"image/x-portable-bitmap","extension"=>[".pbm"]),
Array("name"=>"Portable Compiled Format","mime"=>"application/x-font-pcf","extension"=>[".pcf"]),
Array("name"=>"Portable Font Resource","mime"=>"application/font-tdpfr","extension"=>[".pfr"]),
Array("name"=>"Portable Game Notation (Chess Games)","mime"=>"application/x-chess-pgn","extension"=>[".pgn"]),
Array("name"=>"Portable Graymap Format","mime"=>"image/x-portable-graymap","extension"=>[".pgm"]),
Array("name"=>"Portable Network Graphics (PNG)","mime"=>"image/png","extension"=>[".png"]),
Array("name"=>"Portable Network Graphics (PNG) (Citrix client)","mime"=>"image/x-citrix-png","extension"=>[".png"]),
Array("name"=>"Portable Network Graphics (PNG) (x-token)","mime"=>"image/x-png","extension"=>[".png"]),
Array("name"=>"Portable Pixmap Format","mime"=>"image/x-portable-pixmap","extension"=>[".ppm"]),
Array("name"=>"Portable Symmetric Key Container","mime"=>"application/pskc+xml","extension"=>[".pskcxml"]),
Array("name"=>"PosML","mime"=>"application/vnd.ctc-posml","extension"=>[".pml"]),
Array("name"=>"PostScript","mime"=>"application/postscript","extension"=>[".ai"]),
Array("name"=>"PostScript Fonts","mime"=>"application/x-font-type1","extension"=>[".pfa"]),
Array("name"=>"PowerBuilder","mime"=>"application/vnd.powerbuilder6","extension"=>[".pbd"]),
Array("name"=>"Pretty Good Privacy","mime"=>"application/pgp-encrypted","extension"=>[".pgp"]),
Array("name"=>"Pretty Good Privacy - Signature","mime"=>"application/pgp-signature","extension"=>[".pgp"]),
Array("name"=>"Preview Systems ZipLock/VBox","mime"=>"application/vnd.previewsystems.box","extension"=>[".box"]),
Array("name"=>"Princeton Video Image","mime"=>"application/vnd.pvi.ptid1","extension"=>[".ptid"]),
Array("name"=>"Pronunciation Lexicon Specification","mime"=>"application/pls+xml","extension"=>[".pls"]),
Array("name"=>"Proprietary P&G Standard Reporting System","mime"=>"application/vnd.pg.format","extension"=>[".str"]),
Array("name"=>"Proprietary P&G Standard Reporting System","mime"=>"application/vnd.pg.osasli","extension"=>[".ei6"]),
Array("name"=>"PRS Lines Tag","mime"=>"text/prs.lines.tag","extension"=>[".dsc"]),
Array("name"=>"PSF Fonts","mime"=>"application/x-font-linux-psf","extension"=>[".psf"]),
Array("name"=>"PubliShare Objects","mime"=>"application/vnd.publishare-delta-tree","extension"=>[".qps"]),
Array("name"=>"Qualcomm's Plaza Mobile Internet","mime"=>"application/vnd.pmi.widget","extension"=>[".wg"]),
Array("name"=>"QuarkXpress","mime"=>"application/vnd.quark.quarkxpress","extension"=>[".qxd"]),
Array("name"=>"QUASS Stream Player","mime"=>"application/vnd.epson.esf","extension"=>[".esf"]),
Array("name"=>"QUASS Stream Player","mime"=>"application/vnd.epson.msf","extension"=>[".msf"]),
Array("name"=>"QUASS Stream Player","mime"=>"application/vnd.epson.ssf","extension"=>[".ssf"]),
Array("name"=>"QuickAnime Player","mime"=>"application/vnd.epson.quickanime","extension"=>[".qam"]),
Array("name"=>"Quicken","mime"=>"application/vnd.intu.qfx","extension"=>[".qfx"]),
Array("name"=>"Quicktime Video","mime"=>"video/quicktime","extension"=>[".qt"]),
Array("name"=>"RAR Archive","mime"=>"application/x-rar-compressed","extension"=>[".rar"]),
Array("name"=>"Real Audio Sound","mime"=>"audio/x-pn-realaudio","extension"=>[".ram"]),
Array("name"=>"Real Audio Sound","mime"=>"audio/x-pn-realaudio-plugin","extension"=>[".rmp"]),
Array("name"=>"Really Simple Discovery","mime"=>"application/rsd+xml","extension"=>[".rsd"]),
Array("name"=>"RealMedia","mime"=>"application/vnd.rn-realmedia","extension"=>[".rm"]),
Array("name"=>"RealVNC","mime"=>"application/vnd.realvnc.bed","extension"=>[".bed"]),
Array("name"=>"Recordare Applications","mime"=>"application/vnd.recordare.musicxml","extension"=>[".mxl"]),
Array("name"=>"Recordare Applications","mime"=>"application/vnd.recordare.musicxml+xml","extension"=>[".musicxml"]),
Array("name"=>"Relax NG Compact Syntax","mime"=>"application/relax-ng-compact-syntax","extension"=>[".rnc"]),
Array("name"=>"RemoteDocs R-Viewer","mime"=>"application/vnd.data-vision.rdz","extension"=>[".rdz"]),
Array("name"=>"Resource Description Framework","mime"=>"application/rdf+xml","extension"=>[".rdf"]),
Array("name"=>"RetroPlatform Player","mime"=>"application/vnd.cloanto.rp9","extension"=>[".rp9"]),
Array("name"=>"RhymBox","mime"=>"application/vnd.jisp","extension"=>[".jisp"]),
Array("name"=>"Rich Text Format","mime"=>"application/rtf","extension"=>[".rtf"]),
Array("name"=>"Rich Text Format (RTF)","mime"=>"text/richtext","extension"=>[".rtx"]),
Array("name"=>"ROUTE 66 Location Based Services","mime"=>"application/vnd.route66.link66+xml","extension"=>[".link66"]),
Array("name"=>"RSS - Really Simple Syndication","mime"=>"application/rss+xml","extension"=>[".rss",".xml"]),
Array("name"=>"S Hexdump Format","mime"=>"application/shf+xml","extension"=>[".shf"]),
Array("name"=>"SailingTracker","mime"=>"application/vnd.sailingtracker.track","extension"=>[".st"]),
Array("name"=>"Scalable Vector Graphics (SVG)","mime"=>"image/svg+xml","extension"=>[".svg"]),
Array("name"=>"ScheduleUs","mime"=>"application/vnd.sus-calendar","extension"=>[".sus"]),
Array("name"=>"Search/Retrieve via URL Response Format","mime"=>"application/sru+xml","extension"=>[".sru"]),
Array("name"=>"Secure Electronic Transaction - Payment","mime"=>"application/set-payment-initiation","extension"=>[".setpay"]),
Array("name"=>"Secure Electronic Transaction - Registration","mime"=>"application/set-registration-initiation","extension"=>[".setreg"]),
Array("name"=>"Secured eMail","mime"=>"application/vnd.sema","extension"=>[".sema"]),
Array("name"=>"Secured eMail","mime"=>"application/vnd.semd","extension"=>[".semd"]),
Array("name"=>"Secured eMail","mime"=>"application/vnd.semf","extension"=>[".semf"]),
Array("name"=>"SeeMail","mime"=>"application/vnd.seemail","extension"=>[".see"]),
Array("name"=>"Server Normal Format","mime"=>"application/x-font-snf","extension"=>[".snf"]),
Array("name"=>"Server-Based Certificate Validation Protocol - Validation Policies - Request","mime"=>"application/scvp-vp-request","extension"=>[".spq"]),
Array("name"=>"Server-Based Certificate Validation Protocol - Validation Policies - Response","mime"=>"application/scvp-vp-response","extension"=>[".spp"]),
Array("name"=>"Server-Based Certificate Validation Protocol - Validation Request","mime"=>"application/scvp-cv-request","extension"=>[".scq"]),
Array("name"=>"Server-Based Certificate Validation Protocol - Validation Response","mime"=>"application/scvp-cv-response","extension"=>[".scs"]),
Array("name"=>"Session Description Protocol","mime"=>"application/sdp","extension"=>[".sdp"]),
Array("name"=>"Setext","mime"=>"text/x-setext","extension"=>[".etx"]),
Array("name"=>"SGI Movie","mime"=>"video/x-sgi-movie","extension"=>[".movie"]),
Array("name"=>"Shana Informed Filler","mime"=>"application/vnd.shana.informed.formdata","extension"=>[".ifm"]),
Array("name"=>"Shana Informed Filler","mime"=>"application/vnd.shana.informed.formtemplate","extension"=>[".itp"]),
Array("name"=>"Shana Informed Filler","mime"=>"application/vnd.shana.informed.interchange","extension"=>[".iif"]),
Array("name"=>"Shana Informed Filler","mime"=>"application/vnd.shana.informed.package","extension"=>[".ipk"]),
Array("name"=>"Sharing Transaction Fraud Data","mime"=>"application/thraud+xml","extension"=>[".tfi"]),
Array("name"=>"Shell Archive","mime"=>"application/x-shar","extension"=>[".shar"]),
Array("name"=>"Silicon Graphics RGB Bitmap","mime"=>"image/x-rgb","extension"=>[".rgb"]),
Array("name"=>"SimpleAnimeLite Player","mime"=>"application/vnd.epson.salt","extension"=>[".slt"]),
Array("name"=>"Simply Accounting","mime"=>"application/vnd.accpac.simply.aso","extension"=>[".aso"]),
Array("name"=>"Simply Accounting - Data Import","mime"=>"application/vnd.accpac.simply.imp","extension"=>[".imp"]),
Array("name"=>"SimTech MindMapper","mime"=>"application/vnd.simtech-mindmapper","extension"=>[".twd"]),
Array("name"=>"Sixth Floor Media - CommonSpace","mime"=>"application/vnd.commonspace","extension"=>[".csp"]),
Array("name"=>"SMAF Audio","mime"=>"application/vnd.yamaha.smaf-audio","extension"=>[".saf"]),
Array("name"=>"SMAF File","mime"=>"application/vnd.smaf","extension"=>[".mmf"]),
Array("name"=>"SMAF Phrase","mime"=>"application/vnd.yamaha.smaf-phrase","extension"=>[".spf"]),
Array("name"=>"SMART Technologies Apps","mime"=>"application/vnd.smart.teacher","extension"=>[".teacher"]),
Array("name"=>"SourceView Document","mime"=>"application/vnd.svd","extension"=>[".svd"]),
Array("name"=>"SPARQL - Query","mime"=>"application/sparql-query","extension"=>[".rq"]),
Array("name"=>"SPARQL - Results","mime"=>"application/sparql-results+xml","extension"=>[".srx"]),
Array("name"=>"Speech Recognition Grammar Specification","mime"=>"application/srgs","extension"=>[".gram"]),
Array("name"=>"Speech Recognition Grammar Specification - XML","mime"=>"application/srgs+xml","extension"=>[".grxml"]),
Array("name"=>"Speech Synthesis Markup Language","mime"=>"application/ssml+xml","extension"=>[".ssml"]),
Array("name"=>"SSEYO Koan Play File","mime"=>"application/vnd.koan","extension"=>[".skp"]),
Array("name"=>"Standard Generalized Markup Language (SGML)","mime"=>"text/sgml","extension"=>[".sgml"]),
Array("name"=>"StarOffice - Calc","mime"=>"application/vnd.stardivision.calc","extension"=>[".sdc"]),
Array("name"=>"StarOffice - Draw","mime"=>"application/vnd.stardivision.draw","extension"=>[".sda"]),
Array("name"=>"StarOffice - Impress","mime"=>"application/vnd.stardivision.impress","extension"=>[".sdd"]),
Array("name"=>"StarOffice - Math","mime"=>"application/vnd.stardivision.math","extension"=>[".smf"]),
Array("name"=>"StarOffice - Writer","mime"=>"application/vnd.stardivision.writer","extension"=>[".sdw"]),
Array("name"=>"StarOffice - Writer (Global)","mime"=>"application/vnd.stardivision.writer-global","extension"=>[".sgl"]),
Array("name"=>"StepMania","mime"=>"application/vnd.stepmania.stepchart","extension"=>[".sm"]),
Array("name"=>"Stuffit Archive","mime"=>"application/x-stuffit","extension"=>[".sit"]),
Array("name"=>"Stuffit Archive","mime"=>"application/x-stuffitx","extension"=>[".sitx"]),
Array("name"=>"SudokuMagic","mime"=>"application/vnd.solent.sdkm+xml","extension"=>[".sdkm"]),
Array("name"=>"Sugar Linux Application Bundle","mime"=>"application/vnd.olpc-sugar","extension"=>[".xo"]),
Array("name"=>"Sun Audio - Au file format","mime"=>"audio/basic","extension"=>[".au"]),
Array("name"=>"SundaHus WQ","mime"=>"application/vnd.wqd","extension"=>[".wqd"]),
Array("name"=>"Symbian Install Package","mime"=>"application/vnd.symbian.install","extension"=>[".sis"]),
Array("name"=>"Synchronized Multimedia Integration Language","mime"=>"application/smil+xml","extension"=>[".smi"]),
Array("name"=>"SyncML","mime"=>"application/vnd.syncml+xml","extension"=>[".xsm"]),
Array("name"=>"SyncML - Device Management","mime"=>"application/vnd.syncml.dm+wbxml","extension"=>[".bdm"]),
Array("name"=>"SyncML - Device Management","mime"=>"application/vnd.syncml.dm+xml","extension"=>[".xdm"]),
Array("name"=>"System V Release 4 CPIO Archive","mime"=>"application/x-sv4cpio","extension"=>[".sv4cpio"]),
Array("name"=>"System V Release 4 CPIO Checksum Data","mime"=>"application/x-sv4crc","extension"=>[".sv4crc"]),
Array("name"=>"Systems Biology Markup Language","mime"=>"application/sbml+xml","extension"=>[".sbml"]),
Array("name"=>"Tab Seperated Values","mime"=>"text/tab-separated-values","extension"=>[".tsv"]),
Array("name"=>"Tagged Image File Format","mime"=>"image/tiff","extension"=>[".tiff"]),
Array("name"=>"Tao Intent","mime"=>"application/vnd.tao.intent-module-archive","extension"=>[".tao"]),
Array("name"=>"Tar File (Tape Archive)","mime"=>"application/x-tar","extension"=>[".tar"]),
Array("name"=>"Tcl Script","mime"=>"application/x-tcl","extension"=>[".tcl"]),
Array("name"=>"TeX","mime"=>"application/x-tex","extension"=>[".tex"]),
Array("name"=>"TeX Font Metric","mime"=>"application/x-tex-tfm","extension"=>[".tfm"]),
Array("name"=>"Text Encoding and Interchange","mime"=>"application/tei+xml","extension"=>[".tei"]),
Array("name"=>"Text File","mime"=>"text/plain","extension"=>[".txt"]),
Array("name"=>"TIBCO Spotfire","mime"=>"application/vnd.spotfire.dxp","extension"=>[".dxp"]),
Array("name"=>"TIBCO Spotfire","mime"=>"application/vnd.spotfire.sfs","extension"=>[".sfs"]),
Array("name"=>"Time Stamped Data Envelope","mime"=>"application/timestamped-data","extension"=>[".tsd"]),
Array("name"=>"TRI Systems Config","mime"=>"application/vnd.trid.tpt","extension"=>[".tpt"]),
Array("name"=>"Triscape Map Explorer","mime"=>"application/vnd.triscape.mxs","extension"=>[".mxs"]),
Array("name"=>"troff","mime"=>"text/troff","extension"=>[".t"]),
Array("name"=>"True BASIC","mime"=>"application/vnd.trueapp","extension"=>[".tra"]),
Array("name"=>"TrueType Font","mime"=>"application/x-font-ttf","extension"=>[".ttf"]),
Array("name"=>"Turtle (Terse RDF Triple Language)","mime"=>"text/turtle","extension"=>[".ttl"]),
Array("name"=>"UMAJIN","mime"=>"application/vnd.umajin","extension"=>[".umj"]),
Array("name"=>"Unique Object Markup Language","mime"=>"application/vnd.uoml+xml","extension"=>[".uoml"]),
Array("name"=>"Unity 3d","mime"=>"application/vnd.unity","extension"=>[".unityweb"]),
Array("name"=>"Universal Forms Description Language","mime"=>"application/vnd.ufdl","extension"=>[".ufd"]),
Array("name"=>"URI Resolution Services","mime"=>"text/uri-list","extension"=>[".uri"]),
Array("name"=>"User Interface Quartz - Theme (Symbian)","mime"=>"application/vnd.uiq.theme","extension"=>[".utz"]),
Array("name"=>"Ustar (Uniform Standard Tape Archive)","mime"=>"application/x-ustar","extension"=>[".ustar"]),
Array("name"=>"UUEncode","mime"=>"text/x-uuencode","extension"=>[".uu"]),
Array("name"=>"vCalendar","mime"=>"text/x-vcalendar","extension"=>[".vcs"]),
Array("name"=>"vCard","mime"=>"text/x-vcard","extension"=>[".vcf"]),
Array("name"=>"Video CD","mime"=>"application/x-cdlink","extension"=>[".vcd"]),
Array("name"=>"Viewport+","mime"=>"application/vnd.vsf","extension"=>[".vsf"]),
Array("name"=>"Virtual Reality Modeling Language","mime"=>"model/vrml","extension"=>[".wrl"]),
Array("name"=>"VirtualCatalog","mime"=>"application/vnd.vcx","extension"=>[".vcx"]),
Array("name"=>"Virtue MTS","mime"=>"model/vnd.mts","extension"=>[".mts"]),
Array("name"=>"Virtue VTU","mime"=>"model/vnd.vtu","extension"=>[".vtu"]),
Array("name"=>"Visionary","mime"=>"application/vnd.visionary","extension"=>[".vis"]),
Array("name"=>"Vivo","mime"=>"video/vnd.vivo","extension"=>[".viv"]),
Array("name"=>"Voice Browser Call Control","mime"=>"application/ccxml+xml,","extension"=>[".ccxml"]),
Array("name"=>"VoiceXML","mime"=>"application/voicexml+xml","extension"=>[".vxml"]),
Array("name"=>"WAIS Source","mime"=>"application/x-wais-source","extension"=>[".src"]),
Array("name"=>"WAP Binary XML (WBXML)","mime"=>"application/vnd.wap.wbxml","extension"=>[".wbxml"]),
Array("name"=>"WAP Bitamp (WBMP)","mime"=>"image/vnd.wap.wbmp","extension"=>[".wbmp"]),
Array("name"=>"Waveform Audio File Format (WAV)","mime"=>"audio/x-wav","extension"=>[".wav"]),
Array("name"=>"Web Distributed Authoring and Versioning","mime"=>"application/davmount+xml","extension"=>[".davmount"]),
Array("name"=>"Web Open Font Format","mime"=>"application/x-font-woff","extension"=>[".woff"]),
Array("name"=>"Web Services Policy","mime"=>"application/wspolicy+xml","extension"=>[".wspolicy"]),
Array("name"=>"WebP Image","mime"=>"image/webp","extension"=>[".webp"]),
Array("name"=>"WebTurbo","mime"=>"application/vnd.webturbo","extension"=>[".wtb"]),
Array("name"=>"Widget Packaging and XML Configuration","mime"=>"application/widget","extension"=>[".wgt"]),
Array("name"=>"WinHelp","mime"=>"application/winhlp","extension"=>[".hlp"]),
Array("name"=>"Wireless Markup Language (WML)","mime"=>"text/vnd.wap.wml","extension"=>[".wml"]),
Array("name"=>"Wireless Markup Language Script (WMLScript)","mime"=>"text/vnd.wap.wmlscript","extension"=>[".wmls"]),
Array("name"=>"WMLScript","mime"=>"application/vnd.wap.wmlscriptc","extension"=>[".wmlsc"]),
Array("name"=>"Wordperfect","mime"=>"application/vnd.wordperfect","extension"=>[".wpd"]),
Array("name"=>"Worldtalk","mime"=>"application/vnd.wt.stf","extension"=>[".stf"]),
Array("name"=>"WSDL - Web Services Description Language","mime"=>"application/wsdl+xml","extension"=>[".wsdl"]),
Array("name"=>"X BitMap","mime"=>"image/x-xbitmap","extension"=>[".xbm"]),
Array("name"=>"X PixMap","mime"=>"image/x-xpixmap","extension"=>[".xpm"]),
Array("name"=>"X Window Dump","mime"=>"image/x-xwindowdump","extension"=>[".xwd"]),
Array("name"=>"X.509 Certificate","mime"=>"application/x-x509-ca-cert","extension"=>[".der"]),
Array("name"=>"Xfig","mime"=>"application/x-xfig","extension"=>[".fig"]),
Array("name"=>"XHTML - The Extensible HyperText Markup Language","mime"=>"application/xhtml+xml","extension"=>[".xhtml"]),
Array("name"=>"XML - Extensible Markup Language","mime"=>"application/xml","extension"=>[".xml"]),
Array("name"=>"XML Configuration Access Protocol - XCAP Diff","mime"=>"application/xcap-diff+xml","extension"=>[".xdf"]),
Array("name"=>"XML Encryption Syntax and Processing","mime"=>"application/xenc+xml","extension"=>[".xenc"]),
Array("name"=>"XML Patch Framework","mime"=>"application/patch-ops-error+xml","extension"=>[".xer"]),
Array("name"=>"XML Resource Lists","mime"=>"application/resource-lists+xml","extension"=>[".rl"]),
Array("name"=>"XML Resource Lists","mime"=>"application/rls-services+xml","extension"=>[".rs"]),
Array("name"=>"XML Resource Lists Diff","mime"=>"application/resource-lists-diff+xml","extension"=>[".rld"]),
Array("name"=>"XML Transformations","mime"=>"application/xslt+xml","extension"=>[".xslt"]),
Array("name"=>"XML-Binary Optimized Packaging","mime"=>"application/xop+xml","extension"=>[".xop"]),
Array("name"=>"XPInstall - Mozilla","mime"=>"application/x-xpinstall","extension"=>[".xpi"]),
Array("name"=>"XSPF - XML Shareable Playlist Format","mime"=>"application/xspf+xml","extension"=>[".xspf"]),
Array("name"=>"XUL - XML User Interface Language","mime"=>"application/vnd.mozilla.xul+xml","extension"=>[".xul"]),
Array("name"=>"XYZ File Format","mime"=>"chemical/x-xyz","extension"=>[".xyz"]),
Array("name"=>"YAML Ain't Markup Language / Yet Another Markup Language","mime"=>"text/yaml","extension"=>[".yaml"]),
Array("name"=>"YANG Data Modeling Language","mime"=>"application/yang","extension"=>[".yang"]),
Array("name"=>"YIN (YANG - XML)","mime"=>"application/yin+xml","extension"=>[".yin"]),
Array("name"=>"Z.U.L. Geometry","mime"=>"application/vnd.zul","extension"=>[".zir"]),
Array("name"=>"Zip Archive","mime"=>"application/zip","extension"=>[".zip"]),
Array("name"=>"ZVUE Media Manager","mime"=>"application/vnd.handheld-entertainment+xml","extension"=>[".zmm"]),
Array("name"=>"Zzazz Deck","mime"=>"application/vnd.zzazz.deck+xml","extension"=>[".zaz"])];

function mime_to_ext($mime){
  global $mime_db;
  $res = array_search($mime, array_column($mime_db, 'mime'));
  if($res!==false){
    return $mime_db[$res]["extension"][0];
  }else{
    return ".";
  }
}
?>
